class: Juggernaut
name: 'Notepad'
comboKey: 'shift'
skill01: '1'
skill02: '2'
skill03: '3'
skill04: '4'
skill05: '5'
skill06: '6'
skill07: '7'
skill08: '8'
skill09: '9'
skill10: '0'
skill11: ','
skill12: '.'
